[BK-151] Update titan bridge based latest design
tokamak-network/tokamak-bridge pull request #296
Opened 2024-11-05 07:44 UTC by vihsonic

## Summary

- Titan bridge design change
https://www.figma.com/design/4gtlnQ5CJRbnU3PHdbwHTV/BEE%3A-2024?node-id=743-3474&node-type=canvas&t=YDFHAJaXSUe7sysr-0

## Checklist

- [ ] Provided a screenshot (only if change is visible in UI)
- [ ] Provided steps for playback (only if possible).
- [ ] Provided a change scope in summary
- [ ] Local build has passed

2024-11-05 08:52 UTC, SonYoungsung commented
1. gasLimit doesn't seem to match the UI
![image](https://github.com/user-attachments/assets/bb420f0d-5a2e-42d8-8a2f-474b36d1e6db)
![image](https://github.com/user-attachments/assets/50cbc491-c587-4f45-bbfe-3100213a53b2)

2. usd price is wrong, might be floating point issue
![image](https://github.com/user-attachments/assets/6feba6ed-a2b4-4f06-b78f-32988ffa20de)

2024-11-06 06:50 UTC, SonYoungsung requested changes

2024-11-06 06:54 UTC, vihsonic commented on src/staging/components/new-confirm/hooks/useGetGas.ts
> +  const CLAIM_GAS_USED = 916938;
my bad! I knew it but did a commit without saving.

2024-11-06 07:32 UTC, vihsonic commented on src/hooks/price/useGetMarketPrice.ts
> +      const amount = Number(params.amount) < 0.00001 ? 0.0 : Number(params.amount);
updated.

2024-11-06 07:42 UTC, SonYoungsung approved these changes

2024-11-06 07:46 UTC, merged

2024-11-06 07:49 UTC, SonYoungsung commented on src/hooks/price/useGetMarketPrice.ts
> +      const result = price.times(amount).toNumber();
If toNumber() is used to convert it back to a JavaScript number type, the floating-point issue will occur in the same way. The current return type is number, so it seems to have been adjusted this way. However, changing the return type to string and modifying the places where the hook is used to handle type errors might be necessary to ensure the UI displays based on the string. If this task takes too long, it would be fine to prioritize other issues first.

2024-11-06 07:55 UTC, vihsonic commented on src/hooks/price/useGetMarketPrice.ts
> +      const result = price.times(amount).toNumber();
As far as I tested decimal.js, it works fine meaning that the `price.times(amount)` is correct value.
And when we convert it to js Number, it works even for `1.034e-18`. I think it is enough for us.
The problem we had before was that when we convert that value(number) to string to show on the UI.
That's why I returned 0.0 when the value is less than 0.0001 here.
What is your thought? @SonYoungsung

2024-11-06 08:04 UTC, SonYoungsung commented on src/hooks/price/useGetMarketPrice.ts
> +      const result = price.times(amount).toNumber();
yeah, i think you are right. I thought we need to support for more decimals but actually it turns out it's needed. When it comes to the UI, we only need to consider 2 decimal places for USD value. Thanks for checking!